# Generated by Django 2.2.7 on 2019-11-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('img', models.ImageField(null=True, upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.TextField(max_length=100)),
            ],
        ),
    ]
