# Generated by Django 2.2.7 on 2019-11-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20191119_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='category',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='subcategory',
        ),
    ]
