# Generated by Django 2.2.7 on 2019-11-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20191120_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fav_clothes',
            field=models.ManyToManyField(to='data.Cloth'),
        ),
    ]
