# Generated by Django 2.2.7 on 2019-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_person_fav_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='fav_by',
            field=models.ManyToManyField(to='data.Person'),
        ),
    ]
