# Generated by Django 2.2.7 on 2019-11-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_cloth_fav_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('clothes', models.ManyToManyField(to='data.Cloth')),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='key_words',
            field=models.ManyToManyField(to='data.Keywords'),
        ),
    ]
