# Generated by Django 2.2.7 on 2019-12-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20191121_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
