# Generated by Django 2.2.7 on 2019-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20191201_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
