export const GET_CLOTHES = 'GET_CLOTHES'
export const CLEAR_CLOTHES = 'CLEAR_CLOTHES'
export const REMOVE_CLOTH = 'REMOVE_CLOTH'

export const GET_USER_SETTING = 'GET_USER_SETTING'
export const SET_DEFAULT_SETTINGS = 'SET_DEFAULT_SETTINGS'